### ISSUE TITLE
Using from code

### ISSUE THREAD

**Issue by epoberezkin** [MatAtBread/nodent#16]
It would help if it were better documented.

I am doing this:

```
var nodent = require('nodent')(); // I expect it to return a compiler instance
var pr = nodent.compile(code);
code = nodent.prettyPrint(pr).code;
```

`code` is (beautified, there are no line-breaks in the code I pass):
```
validate = async function(data, dataPath) {
  'use strict';
  if (typeof data === "string") {
    if (!(await formats.english_word.validate(data))) {
      throw new ValidationError([{
        keyword: 'format',
        dataPath: (dataPath || '') + "",
        schemaPath: "#/format",
        params: { format: 'english_word' },
        message: 'should match format "english_word"'
      }]);
    }
  } else {
    throw new ValidationError([{
      keyword: 'type',
      dataPath: (dataPath || '') + "",
      schemaPath: "#/type",
      params: { type: 'string' },
      message: 'should be string'
    }]);
  }
  return true;
};
```

It fails on `nodent.compile` call with "TypeError: Cannot read property 'split' of undefined". Doesn't give me line in nodent for some reason...

**Comment by epoberezkin** [comment]
Ok, the error is caught in nodent it seems... This is where it throws first:
```
TypeError: Cannot read property 'split' of undefined
    at NodentCompiler.prettyPrint (/Users/evgenypoberezkin/JSON/ajv/node_modules/nodent/nodent.js:281:28)
    at NodentCompiler.compile (/Users/evgenypoberezkin/JSON/ajv/node_modules/nodent/nodent.js:458:7)
```

**Comment by epoberezkin** [comment]
It seems that I can do just:
```
var code = nodent.compile(code).code;
```

Still throws though

**Comment by matAtWork** [comment]
You need to pass a "filename" to compile (used to generate sourcemaps). It can be faked. Try:

```
nodent.compile(sourceCode,""/*filename*/,{promises:true}) ;
```

There's a resasonble example in the online-demo code at https://github.com/MatAtBread/nodent-demo/blob/master/demo.js#L60

**Comment by matAtWork** [comment]
...and you're right, these APIs need documenting properly

**Comment by epoberezkin** [comment]
It's working... Almost always :)
