### ISSUE TITLE
nodent dont work?

### ISSUE THREAD

**Issue by csakaszamok** [MatAtBread/nodent#42]
hi,

i created a simple app (app.js) and installed nodent (npm install nodent):

`var nodent = require('nodent')() ;`
`//'use nodent-es7';`
`//'use strict';`
`async function tellYouLater(sayWhat) {`
`    // Do something asynchronous and terminal, such as DB access, web access, etc.`
`    return sayWhat;`
`}`
`var result = await tellYouLater("Hi there") ;`

but when i run this code (node app.js):

async function tellYouLater(sayWhat) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:575:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by matAtWork** [comment]
You need to put the `var nodent = require('nodent')()` in a file of it's own, before your `require` modules that use `async` or `await`. 

From the README, in https://github.com/MatAtBread/nodent/blob/master/README.md#basic-use-and-syntax

> You can't use the directive, or any other Nodent features in the file that initially require("nodent")(). If necessary, have a simple "loader.js" that requires Nodent and then requires your first Nodented file, or start your app with nodent from the command line:
