### ISSUE TITLE
Handling of ES6 templates seems to be broken

### ISSUE THREAD

**Issue by medikoo** [MatAtBread/nodent#91]
Following code:

```javascript
`${ foo }`.substr();
```

Crashes compiler with:

```
TypeError: Cannot read property 'match' of undefined
    at Object.MemberExpression (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:777:124)
    at Object.out (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:123:11)
    at Object.expr (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:137:14)
    at Object.CallExpression (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:763:14)
    at Object.out (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:123:11)
    at Object.expr (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:137:14)
    at Object.BinaryExpression (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:734:14)
    at Object.AssignmentExpression (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:742:12)
    at Object.out (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:123:11)
    at Object.expr (/Users/medikoo/Projects/maas/maas-transport-booking/node_modules/nodent/lib/output.js:137:14)
```

Can be reproduced on [demo page](http://nodent.mailed.me.uk/#%60%24%7B%20foo%20%7D%60.substr()%3B~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Atrue%2C%22es6target%22%3Atrue%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D)

**Comment by matAtWork** [comment]
Fixed by https://github.com/MatAtBread/nodent/commit/f595f7b521960722b3c8755b95d75d407900197f in v3.0.20.

Thanks for the report 👍

**Comment by medikoo** [comment]
Thank you! 👍  :)
